# \u6570\u636E\u5E93\u7684\u8FDE\u63A5\u65B0
spring:
  datasource:
    username: root
    password: zaxscdvf
    url: jdbc:mysql://localhost:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        client-ip: localhost
        dashboard: localhost:8080
        port: 8719
  application:
    name: mall-product
  # \u7EDF\u4E00\u7684\u5168\u5C40\u7684--\u8BBE\u7F6E\u670D\u52A1\u5668\u54CD\u5E94\u7ED9\u5BA2\u6237\u7AEF\u7684\u65E5\u671F\u65F6\u95F4\u683C\u5F0F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # \u5173\u95EDThymeleaf\u7684\u7F13\u5B58
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis # SpringCache \u7F13\u5B58\u7684\u7C7B\u578B\u662F Redis
    redis:
      time-to-live: 60000 # \u6307\u5B9A\u7F13\u5B58key\u7684\u8FC7\u671F\u65F6\u95F4
      # key-prefix: bobo_
      use-key-prefix: true
      cache-null-values: true # \u662F\u5426\u7F13\u5B58\u7A7A\u503C\uFF0C\u9632\u6B62\u7F13\u5B58\u7A7F\u900F
  session:
    store-type: redis
    redis:
      namespace: spring:session
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-value: 1 # 逻辑已删除值（默认1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）

server:
  port: 8040
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  sentinel:
    enabled: true
